#=================================================
# https://github.com/zhangsean/docker-frp
# Description: Auto check latest frp release and tag zhangsean/frp using GitHub Actions
# License: Apache V2.0
# Author: ZhangSean
#=================================================

name: Follow up frp release

on:
  schedule:
    - cron: 1 15 * * *
  watch:
    types: [started]
    if: github.event.repository.owner.id == github.event.sender.id
  push:
    paths:
      - '.github/workflows/*.yml'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check frp release
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git fetch --tags
          export CURRENT=$(git tag | tail -n 1)
          echo "CURRENT=$CURRENT"
          export LATEST=$(curl -sSI https://github.com/fatedier/frp/releases/latest | sed -n '/frp/s/.*\(v.*\)./\1/p')
          echo "LATEST=$LATEST"
          if [ "$LATEST" != "$CURRENT" ]; then
            echo "New frp release: $LATEST"
            echo "CURRENT=$CURRENT" >> $GITHUB_ENV
            echo "LATEST=$LATEST" >> $GITHUB_ENV
          else
            echo "No new frp release"
            echo "LATEST=" >> $GITHUB_ENV
          fi

      - name: Bump to new frp version
        if: success() && env.CURRENT != '' && env.LATEST != ''
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Bump frp version from $CURRENT to $LATEST"
          sed -i "/FRP_VERSION/s/$CURRENT/$LATEST/g" Dockerfile
          sed -i "/latest/a * $LATEST" README.md
          # commit and push
          git config user.email zxf2342@qq.com
          git config user.name zhangsean
          git commit -a -m "Bump to frp $LATEST"
          git push
          git tag "$LATEST"
          git push --tags
          export SHA=$(git branch -v | awk '{print $3}')
          echo "SHA=$SHA" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        if: success() && env.LATEST != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST }}
          release_name: ${{ env.LATEST }}
          body: |
            Bump to frp ${{ env.LATEST }}
          draft: false
          prerelease: false

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: success() && env.LATEST != ''
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success() && env.LATEST != ''
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: success() && env.LATEST != ''
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        if: success() && env.LATEST != ''
        with:
          context: .
          push: true
          tags: |
            zhangsean/frp:latest,
            zhangsean/frp:${{ env.LATEST }}
